<a href="https://colab.research.google.com/github/bmoazen/Credit_Risk_Analysis/blob/main/credit_risk_resampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Credit Risk Resampling Techniques

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [3]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
from google.colab import files
uploaded = files.upload()

file_name='LoanStats_2019Q1.csv'
df = pd.read_csv(file_name, skiprows=1)[:-2]

Saving LoanStats_2019Q1.csv to LoanStats_2019Q1.csv


In [ ]:
len(df.index)

In [85]:
df2=df.loc[:, columns].copy()

# Drop the null columns where all values are null
df2 = df2.dropna(axis='columns', how='all')

# Drop the null rows
df2 = df2.dropna()

# Remove the `Issued` loan status
issued_mask = df2['loan_status'] != 'Issued'
df2 = df2.loc[issued_mask]

# convert interest rate to numerical
df2['int_rate'] = df2['int_rate'].str.replace('%', '')
df2['int_rate'] = df2['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df2 = df2.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df2 = df2.replace(x)

df2.reset_index(inplace=True, drop=True)

df2.head()

loan_amnt  int_rate  ...  hardship_flag debt_settlement_flag
0    10500.0    0.1719  ...              N                    N
1    25000.0    0.2000  ...              N                    N
2    20000.0    0.2000  ...              N                    N
3    10000.0    0.1640  ...              N                    N
4    22000.0    0.1474  ...              N                    N

[5 rows x 86 columns]

# Split the Data into Training and Testing

In [87]:
# Create our features
X = df2.copy()
X=X.drop("loan_status",axis=1)

# Need to convert columns with strings to numeric
# Get column names that are non-numeric
column_names=X.select_dtypes(exclude=[np.number]).columns
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for columnName in column_names:
  X[columnName]=le.fit_transform(X[columnName])

# Create our target
y = df2['loan_status'].copy()

In [88]:
X.head()

loan_amnt  int_rate  ...  hardship_flag  debt_settlement_flag
0    10500.0    0.1719  ...              0                     0
1    25000.0    0.2000  ...              0                     0
2    20000.0    0.2000  ...              0                     0
3    10000.0    0.1640  ...              0                     0
4    22000.0    0.1474  ...              0                     0

[5 rows x 85 columns]

In [89]:
X.describe()

loan_amnt      int_rate  ...  hardship_flag  debt_settlement_flag
count  68817.000000  68817.000000  ...        68817.0               68817.0
mean   16677.594562      0.127718  ...            0.0                   0.0
std    10277.348590      0.048130  ...            0.0                   0.0
min     1000.000000      0.060000  ...            0.0                   0.0
25%     9000.000000      0.088100  ...            0.0                   0.0
50%    15000.000000      0.118000  ...            0.0                   0.0
75%    24000.000000      0.155700  ...            0.0                   0.0
max    40000.000000      0.308400  ...            0.0                   0.0

[8 rows x 85 columns]

In [90]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Scale the Data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [102]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({'high_risk': 51357, 'low_risk': 51357})

In [103]:
y_resampled

0          low_risk
1          low_risk
2          low_risk
3          low_risk
4          low_risk
            ...    
102709    high_risk
102710    high_risk
102711    high_risk
102712    high_risk
102713    high_risk
Name: loan_status, Length: 102714, dtype: object

In [96]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [97]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.6198091204500011

In [98]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[   54,    38],
       [ 5944, 11169]])

In [100]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.59      0.65      0.02      0.62      0.38        92
   low_risk       1.00      0.65      0.59      0.79      0.62      0.39     17113

avg / total       0.99      0.65      0.59      0.78      0.62      0.39     17205



### SMOTE Oversampling

In [119]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,
                                 sampling_strategy='auto').fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({'high_risk': 51357, 'low_risk': 51357})

In [120]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [121]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6345649379190496

In [61]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)


array([[   57,    35],
       [ 5997, 11116]])

In [62]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.62      0.65      0.02      0.63      0.40        92
   low_risk       1.00      0.65      0.62      0.79      0.63      0.40     17113

avg / total       0.99      0.65      0.62      0.78      0.63      0.40     17205



# Undersampling - Cluster Centroids

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [110]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete

from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({'high_risk': 255, 'low_risk': 255})

In [115]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [116]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5055684846760282

In [117]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)


array([[  54,   38],
       [9854, 7259]])

In [118]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))


                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.59      0.42      0.01      0.50      0.25        92
   low_risk       0.99      0.42      0.59      0.59      0.50      0.24     17113

avg / total       0.99      0.43      0.59      0.59      0.50      0.24     17205



# Combination (Over and Under) Sampling - SMOTEENN

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [105]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN

sme = SMOTEENN(random_state=1)
X_res, y_res = sme.fit_resample(X, y)

Counter(y_res)

Counter({'high_risk': 68458, 'low_risk': 62022})

In [106]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [107]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6345649379190496

In [108]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   57,    35],
       [ 5997, 11116]])

In [109]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.62      0.65      0.02      0.63      0.40        92
   low_risk       1.00      0.65      0.62      0.79      0.63      0.40     17113

avg / total       0.99      0.65      0.62      0.78      0.63      0.40     17205

